-- ComputeLayer schema (spec §6, plus the V0.2 cross-model reuse slice), as
-- raw DDL.
--
-- Alembic revisions 0001+0002 are what actually run; this file is the
-- readable reference and is verified to apply cleanly to PostgreSQL 16.

CREATE TABLE workspaces (
    id          UUID PRIMARY KEY,
    name        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE projects (
    id            UUID PRIMARY KEY,
    workspace_id  UUID NOT NULL REFERENCES workspaces (id),
    name          TEXT NOT NULL,
    slug          TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, slug)
);
CREATE INDEX ix_projects_workspace_id ON projects (workspace_id);

-- §56: keys are stored hashed and scoped to a project.
CREATE TABLE api_keys (
    id            UUID PRIMARY KEY,
    workspace_id  UUID NOT NULL REFERENCES workspaces (id),
    project_id    UUID REFERENCES projects (id),
    name          TEXT NOT NULL,
    key_prefix    TEXT NOT NULL,
    key_hash      TEXT NOT NULL UNIQUE,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    last_used_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_api_keys_key_prefix   ON api_keys (key_prefix);
CREATE INDEX ix_api_keys_workspace_id ON api_keys (workspace_id);
CREATE INDEX ix_api_keys_project_id   ON api_keys (project_id);

-- §6.3
CREATE TABLE runs (
    id                   UUID PRIMARY KEY,
    workspace_id         UUID NOT NULL REFERENCES workspaces (id),
    project_id           UUID NOT NULL REFERENCES projects (id),
    external_run_id      TEXT,
    status               TEXT NOT NULL,
    metadata             JSONB NOT NULL DEFAULT '{}',
    total_input_tokens   BIGINT NOT NULL DEFAULT 0,
    total_output_tokens  BIGINT NOT NULL DEFAULT 0,
    estimated_cost_usd   NUMERIC(18, 8) NOT NULL DEFAULT 0,
    estimated_saved_usd  NUMERIC(18, 8) NOT NULL DEFAULT 0,
    started_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at          TIMESTAMPTZ,
    CONSTRAINT ck_runs_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED'))
);
CREATE INDEX ix_runs_workspace_id ON runs (workspace_id);
CREATE INDEX ix_runs_project_id   ON runs (project_id);

-- §6.4
CREATE TABLE computations (
    id                UUID PRIMARY KEY,
    -- Monotonic insertion order. "Newest valid computation" is resolved by this
    -- rather than created_at, which defaults to now() -- transaction time --
    -- and therefore ties for any rows written in a single transaction.
    seq               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    workspace_id      UUID NOT NULL REFERENCES workspaces (id),
    project_id        UUID NOT NULL REFERENCES projects (id),
    run_id            UUID REFERENCES runs (id),
    name              TEXT NOT NULL,
    logical_key       TEXT NOT NULL,
    fingerprint       TEXT NOT NULL,
    status            TEXT NOT NULL,
    cache_status      TEXT NOT NULL,
    input_json        JSONB,
    output_json       JSONB,
    output_hash       TEXT,
    model             TEXT,
    provider          TEXT,
    prompt_hash       TEXT,
    tool_schema_hash  TEXT,
    code_version      TEXT,
    input_tokens      BIGINT NOT NULL DEFAULT 0,
    output_tokens     BIGINT NOT NULL DEFAULT 0,
    cost_usd          NUMERIC(18, 8) NOT NULL DEFAULT 0,
    saved_usd         NUMERIC(18, 8) NOT NULL DEFAULT 0,
    latency_ms        BIGINT,
    ttl_seconds       BIGINT,
    reusable          BOOLEAN NOT NULL DEFAULT TRUE,
    -- Set on HIT observation rows: the computation whose output was reused.
    -- A real column rather than a metadata key, so "tokens avoided" is an
    -- indexed join instead of a cast out of JSONB.
    reused_from       UUID REFERENCES computations (id),
    metadata          JSONB NOT NULL DEFAULT '{}',
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at      TIMESTAMPTZ,
    expires_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- V0.2 cross-model reuse (added in revision 0002). All nullable, no
    -- backfill: rows written before 0002 are simply unclassified and
    -- ineligible as cross-model sources.
    model_agnostic_fingerprint  TEXT,
    artifact_type               TEXT,
    reuse_kind                  TEXT,
    CONSTRAINT ck_computations_status
        CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_computations_cache_status
        CHECK (cache_status IN ('HIT', 'MISS', 'STALE', 'FORCED')),
    -- §6.4 says CHAR(64). CHAR does not enforce a hex digest, and PostgreSQL
    -- casts bpchar to text when compared against a text parameter, which makes
    -- the column's own index unusable from the driver. TEXT + a format check
    -- gives the real guarantee and keeps the indexes usable.
    CONSTRAINT ck_computations_fingerprint_hex
        CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_computations_logical_key_hex
        CHECK (logical_key ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_computations_output_hash_hex
        CHECK (output_hash IS NULL OR output_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_computations_model_agnostic_fingerprint_hex
        CHECK (model_agnostic_fingerprint IS NULL
               OR model_agnostic_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_computations_artifact_type
        CHECK (artifact_type IS NULL OR artifact_type IN (
            'source', 'fact', 'structured_data', 'research_note',
            'analysis', 'draft', 'citation'
        )),
    CONSTRAINT ck_computations_reuse_kind
        CHECK (reuse_kind IS NULL OR reuse_kind IN ('CROSS_MODEL'))
);

CREATE INDEX idx_computations_fingerprint
    ON computations (workspace_id, project_id, fingerprint);

CREATE INDEX idx_computations_logical_key
    ON computations (workspace_id, project_id, logical_key);

CREATE INDEX idx_computations_run         ON computations (run_id);
CREATE INDEX idx_computations_reused_from ON computations (reused_from);
CREATE INDEX idx_computations_created ON computations (created_at DESC);

-- Partial indexes covering exactly the rows each lookup may return, so the §58
-- p95 target does not degrade as history accumulates. Measured over 50k rows:
-- 0.08 ms indexed vs 12.8 ms sequential.
--
-- Queries must spell the predicate `reusable = TRUE`. PostgreSQL will not prove
-- that `reusable IS TRUE` implies it and silently falls back to a seq scan.
CREATE INDEX idx_computations_reusable
    ON computations (workspace_id, project_id, fingerprint, seq DESC)
    WHERE status = 'SUCCEEDED' AND reusable = TRUE;

CREATE INDEX idx_computations_logical_reusable
    ON computations (workspace_id, project_id, logical_key, seq DESC)
    WHERE status = 'SUCCEEDED';

-- §6.5
CREATE TABLE computation_dependencies (
    id                     UUID PRIMARY KEY,
    computation_id         UUID NOT NULL
                               REFERENCES computations (id) ON DELETE CASCADE,
    dependency_key         TEXT NOT NULL,
    dependency_version     TEXT NOT NULL,
    dependency_type        TEXT NOT NULL DEFAULT 'EXTERNAL',
    source_computation_id  UUID REFERENCES computations (id),
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (computation_id, dependency_key),
    CONSTRAINT ck_dependency_type CHECK (
        dependency_type IN
        ('EXTERNAL', 'COMPUTATION', 'FILE', 'API', 'DATABASE', 'MANUAL')
    )
);
CREATE INDEX idx_dependencies_key
    ON computation_dependencies (dependency_key, dependency_version);
CREATE INDEX idx_dependencies_source
    ON computation_dependencies (source_computation_id);

-- §6.6
CREATE TABLE resources (
    id               UUID PRIMARY KEY,
    workspace_id     UUID NOT NULL REFERENCES workspaces (id),
    project_id       UUID NOT NULL REFERENCES projects (id),
    resource_key     TEXT NOT NULL,
    current_version  TEXT NOT NULL,
    metadata         JSONB NOT NULL DEFAULT '{}',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, project_id, resource_key)
);

-- §6.7
CREATE TABLE computation_events (
    id              BIGSERIAL PRIMARY KEY,
    computation_id  UUID NOT NULL
                        REFERENCES computations (id) ON DELETE CASCADE,
    event_type      TEXT NOT NULL,
    payload         JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_events_computation ON computation_events (computation_id, id);

-- V0.2 cross-model reuse: per-workspace/per-project portability policy.
-- A project_id IS NULL row is the workspace-wide default; a project_id
-- IS NOT NULL row overrides it for that project. Resolution order: project
-- row -> workspace row -> hardcoded fallback default (see
-- app.services.artifact_policy).
CREATE TABLE artifact_type_policies (
    id             UUID PRIMARY KEY,
    workspace_id   UUID NOT NULL REFERENCES workspaces (id),
    project_id     UUID REFERENCES projects (id),
    artifact_type  TEXT NOT NULL,
    portable       BOOLEAN NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_artifact_policy_type
        CHECK (artifact_type IN (
            'source', 'fact', 'structured_data', 'research_note',
            'analysis', 'draft', 'citation'
        ))
);
CREATE INDEX ix_artifact_type_policies_workspace_id
    ON artifact_type_policies (workspace_id);
CREATE INDEX ix_artifact_type_policies_project_id
    ON artifact_type_policies (project_id);
-- NULL is never equal to NULL in SQL, so a plain UNIQUE(workspace_id,
-- project_id, artifact_type) would let unlimited duplicate workspace-default
-- rows (project_id IS NULL) through. Two partial unique indexes instead.
CREATE UNIQUE INDEX ux_artifact_policy_workspace_default
    ON artifact_type_policies (workspace_id, artifact_type)
    WHERE project_id IS NULL;
CREATE UNIQUE INDEX ux_artifact_policy_project_override
    ON artifact_type_policies (workspace_id, project_id, artifact_type)
    WHERE project_id IS NOT NULL;
